name: example
description: A Flutter project to demonstrate the use of the mtg_symbology package.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  mtg_symbology:
    path: ../

dev_dependencies:
  flutter_lints: ^6.0.0
